// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.33.0
// source: proto/handshake.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Handshake message - minimal, fits in small MTU (~150 bytes)
// Exchanged immediately on connection to establish photo sync state
type HandshakeMessage struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	DeviceId        string                 `protobuf:"bytes,1,opt,name=device_id,json=deviceId,proto3" json:"device_id,omitempty"`
	FirstName       string                 `protobuf:"bytes,2,opt,name=first_name,json=firstName,proto3" json:"first_name,omitempty"`
	ProtocolVersion int32                  `protobuf:"varint,3,opt,name=protocol_version,json=protocolVersion,proto3" json:"protocol_version,omitempty"`
	RxPhotoHash     string                 `protobuf:"bytes,4,opt,name=rx_photo_hash,json=rxPhotoHash,proto3" json:"rx_photo_hash,omitempty"` // Hash of photo we RECEIVED from remote device
	TxPhotoHash     string                 `protobuf:"bytes,5,opt,name=tx_photo_hash,json=txPhotoHash,proto3" json:"tx_photo_hash,omitempty"` // Hash of OUR photo available to send
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *HandshakeMessage) Reset() {
	*x = HandshakeMessage{}
	mi := &file_proto_handshake_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HandshakeMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HandshakeMessage) ProtoMessage() {}

func (x *HandshakeMessage) ProtoReflect() protoreflect.Message {
	mi := &file_proto_handshake_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HandshakeMessage.ProtoReflect.Descriptor instead.
func (*HandshakeMessage) Descriptor() ([]byte, []int) {
	return file_proto_handshake_proto_rawDescGZIP(), []int{0}
}

func (x *HandshakeMessage) GetDeviceId() string {
	if x != nil {
		return x.DeviceId
	}
	return ""
}

func (x *HandshakeMessage) GetFirstName() string {
	if x != nil {
		return x.FirstName
	}
	return ""
}

func (x *HandshakeMessage) GetProtocolVersion() int32 {
	if x != nil {
		return x.ProtocolVersion
	}
	return 0
}

func (x *HandshakeMessage) GetRxPhotoHash() string {
	if x != nil {
		return x.RxPhotoHash
	}
	return ""
}

func (x *HandshakeMessage) GetTxPhotoHash() string {
	if x != nil {
		return x.TxPhotoHash
	}
	return ""
}

// Profile message - detailed info, sent after handshake
// Can be fragmented if it exceeds MTU
type ProfileMessage struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DeviceId      string                 `protobuf:"bytes,1,opt,name=device_id,json=deviceId,proto3" json:"device_id,omitempty"`
	LastName      string                 `protobuf:"bytes,2,opt,name=last_name,json=lastName,proto3" json:"last_name,omitempty"`
	PhoneNumber   string                 `protobuf:"bytes,3,opt,name=phone_number,json=phoneNumber,proto3" json:"phone_number,omitempty"`
	Tagline       string                 `protobuf:"bytes,4,opt,name=tagline,proto3" json:"tagline,omitempty"`
	Insta         string                 `protobuf:"bytes,5,opt,name=insta,proto3" json:"insta,omitempty"`
	Linkedin      string                 `protobuf:"bytes,6,opt,name=linkedin,proto3" json:"linkedin,omitempty"`
	Youtube       string                 `protobuf:"bytes,7,opt,name=youtube,proto3" json:"youtube,omitempty"`
	Tiktok        string                 `protobuf:"bytes,8,opt,name=tiktok,proto3" json:"tiktok,omitempty"`
	Gmail         string                 `protobuf:"bytes,9,opt,name=gmail,proto3" json:"gmail,omitempty"`
	Imessage      string                 `protobuf:"bytes,10,opt,name=imessage,proto3" json:"imessage,omitempty"`
	Whatsapp      string                 `protobuf:"bytes,11,opt,name=whatsapp,proto3" json:"whatsapp,omitempty"`
	Signal        string                 `protobuf:"bytes,12,opt,name=signal,proto3" json:"signal,omitempty"`
	Telegram      string                 `protobuf:"bytes,13,opt,name=telegram,proto3" json:"telegram,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProfileMessage) Reset() {
	*x = ProfileMessage{}
	mi := &file_proto_handshake_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProfileMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProfileMessage) ProtoMessage() {}

func (x *ProfileMessage) ProtoReflect() protoreflect.Message {
	mi := &file_proto_handshake_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProfileMessage.ProtoReflect.Descriptor instead.
func (*ProfileMessage) Descriptor() ([]byte, []int) {
	return file_proto_handshake_proto_rawDescGZIP(), []int{1}
}

func (x *ProfileMessage) GetDeviceId() string {
	if x != nil {
		return x.DeviceId
	}
	return ""
}

func (x *ProfileMessage) GetLastName() string {
	if x != nil {
		return x.LastName
	}
	return ""
}

func (x *ProfileMessage) GetPhoneNumber() string {
	if x != nil {
		return x.PhoneNumber
	}
	return ""
}

func (x *ProfileMessage) GetTagline() string {
	if x != nil {
		return x.Tagline
	}
	return ""
}

func (x *ProfileMessage) GetInsta() string {
	if x != nil {
		return x.Insta
	}
	return ""
}

func (x *ProfileMessage) GetLinkedin() string {
	if x != nil {
		return x.Linkedin
	}
	return ""
}

func (x *ProfileMessage) GetYoutube() string {
	if x != nil {
		return x.Youtube
	}
	return ""
}

func (x *ProfileMessage) GetTiktok() string {
	if x != nil {
		return x.Tiktok
	}
	return ""
}

func (x *ProfileMessage) GetGmail() string {
	if x != nil {
		return x.Gmail
	}
	return ""
}

func (x *ProfileMessage) GetImessage() string {
	if x != nil {
		return x.Imessage
	}
	return ""
}

func (x *ProfileMessage) GetWhatsapp() string {
	if x != nil {
		return x.Whatsapp
	}
	return ""
}

func (x *ProfileMessage) GetSignal() string {
	if x != nil {
		return x.Signal
	}
	return ""
}

func (x *ProfileMessage) GetTelegram() string {
	if x != nil {
		return x.Telegram
	}
	return ""
}

// Acknowledgment of photo transfer completion
type PhotoCompletionAck struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DeviceId      string                 `protobuf:"bytes,1,opt,name=device_id,json=deviceId,proto3" json:"device_id,omitempty"`
	TransferCrc   uint32                 `protobuf:"fixed32,2,opt,name=transfer_crc,json=transferCrc,proto3" json:"transfer_crc,omitempty"` // CRC-32 of complete photo data
	Success       bool                   `protobuf:"varint,3,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PhotoCompletionAck) Reset() {
	*x = PhotoCompletionAck{}
	mi := &file_proto_handshake_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PhotoCompletionAck) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PhotoCompletionAck) ProtoMessage() {}

func (x *PhotoCompletionAck) ProtoReflect() protoreflect.Message {
	mi := &file_proto_handshake_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PhotoCompletionAck.ProtoReflect.Descriptor instead.
func (*PhotoCompletionAck) Descriptor() ([]byte, []int) {
	return file_proto_handshake_proto_rawDescGZIP(), []int{2}
}

func (x *PhotoCompletionAck) GetDeviceId() string {
	if x != nil {
		return x.DeviceId
	}
	return ""
}

func (x *PhotoCompletionAck) GetTransferCrc() uint32 {
	if x != nil {
		return x.TransferCrc
	}
	return 0
}

func (x *PhotoCompletionAck) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

var File_proto_handshake_proto protoreflect.FileDescriptor

const file_proto_handshake_proto_rawDesc = "" +
	"\n" +
	"\x15proto/handshake.proto\x12\tauraphone\"\xc1\x01\n" +
	"\x10HandshakeMessage\x12\x1b\n" +
	"\tdevice_id\x18\x01 \x01(\tR\bdeviceId\x12\x1d\n" +
	"\n" +
	"first_name\x18\x02 \x01(\tR\tfirstName\x12)\n" +
	"\x10protocol_version\x18\x03 \x01(\x05R\x0fprotocolVersion\x12\"\n" +
	"\rrx_photo_hash\x18\x04 \x01(\tR\vrxPhotoHash\x12\"\n" +
	"\rtx_photo_hash\x18\x05 \x01(\tR\vtxPhotoHash\"\xed\x02\n" +
	"\x0eProfileMessage\x12\x1b\n" +
	"\tdevice_id\x18\x01 \x01(\tR\bdeviceId\x12\x1b\n" +
	"\tlast_name\x18\x02 \x01(\tR\blastName\x12!\n" +
	"\fphone_number\x18\x03 \x01(\tR\vphoneNumber\x12\x18\n" +
	"\atagline\x18\x04 \x01(\tR\atagline\x12\x14\n" +
	"\x05insta\x18\x05 \x01(\tR\x05insta\x12\x1a\n" +
	"\blinkedin\x18\x06 \x01(\tR\blinkedin\x12\x18\n" +
	"\ayoutube\x18\a \x01(\tR\ayoutube\x12\x16\n" +
	"\x06tiktok\x18\b \x01(\tR\x06tiktok\x12\x14\n" +
	"\x05gmail\x18\t \x01(\tR\x05gmail\x12\x1a\n" +
	"\bimessage\x18\n" +
	" \x01(\tR\bimessage\x12\x1a\n" +
	"\bwhatsapp\x18\v \x01(\tR\bwhatsapp\x12\x16\n" +
	"\x06signal\x18\f \x01(\tR\x06signal\x12\x1a\n" +
	"\btelegram\x18\r \x01(\tR\btelegram\"n\n" +
	"\x12PhotoCompletionAck\x12\x1b\n" +
	"\tdevice_id\x18\x01 \x01(\tR\bdeviceId\x12!\n" +
	"\ftransfer_crc\x18\x02 \x01(\aR\vtransferCrc\x12\x18\n" +
	"\asuccess\x18\x03 \x01(\bR\asuccessB-Z+github.com/andrewarrow/auraphone-blue/protob\x06proto3"

var (
	file_proto_handshake_proto_rawDescOnce sync.Once
	file_proto_handshake_proto_rawDescData []byte
)

func file_proto_handshake_proto_rawDescGZIP() []byte {
	file_proto_handshake_proto_rawDescOnce.Do(func() {
		file_proto_handshake_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_handshake_proto_rawDesc), len(file_proto_handshake_proto_rawDesc)))
	})
	return file_proto_handshake_proto_rawDescData
}

var file_proto_handshake_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_proto_handshake_proto_goTypes = []any{
	(*HandshakeMessage)(nil),   // 0: auraphone.HandshakeMessage
	(*ProfileMessage)(nil),     // 1: auraphone.ProfileMessage
	(*PhotoCompletionAck)(nil), // 2: auraphone.PhotoCompletionAck
}
var file_proto_handshake_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_proto_handshake_proto_init() }
func file_proto_handshake_proto_init() {
	if File_proto_handshake_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_handshake_proto_rawDesc), len(file_proto_handshake_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_proto_handshake_proto_goTypes,
		DependencyIndexes: file_proto_handshake_proto_depIdxs,
		MessageInfos:      file_proto_handshake_proto_msgTypes,
	}.Build()
	File_proto_handshake_proto = out.File
	file_proto_handshake_proto_goTypes = nil
	file_proto_handshake_proto_depIdxs = nil
}
